### ISSUE TITLE
Daum 웹툰 크롤러 설계방안

### ISSUE THREAD

**Issue by jadenkim94** [depromeet/webtoon#12]
영상회의 내용을 바탕으로 제가 이해한 바는 다음과 같습니다.

——————— 배치작업 ————————
DaumCrawlerService 가 WebtoonImportService 사용해서 DB 에 업데이트
 * 배치작업은 매일 이루어지고, 매일 해당요일의 웹툰 데이터들이 업데이트 된다. 
———————————————————   -

이런 이해를 바탕으로 제가 구성하고 있는 방안은 다음과 같습니다.
(화요일 배치작업을 가정하겠습니다) 
다음 API 구조상 화요일의 웹툰 데이터들을 인기순으로 가져오기 위해서 제가 진행하고 있는 작업은 다음과 같습니다. 
1. 인기순 (1~100) 웹툰을 가져온다 
2. 화요일 웹툰을 가져온다
3. 인기순 리스트에서 화요일 웹툰리스트와 같은 웹툰이 있다면 순서대로 저장한다
4. 인기순에 없는 화요일 웹툰리스트도 저장한다 

=> 화요일 인기순대로 정렬을 완료하였습니다.

단, 여기서 장르정보를 긁어올 방법이 없습니다. 따라서 웹툰의 nickname 을 이용해 상세보기로 들어가서 장르정보를 가져와 
WebtoonImportRequest 를 생성하고 생성된 정보를 바탕으로 importWebtoon 을 진행할 것입니다. 

----------- 질문 -----------  
구조가 변경되기 전 가이드 짜주신 코드는 다음과 같습니다. 
```
DaumCrawlService(daumRequestAdapter:DaumRequestAdapter) {
    getPopularWebtoons() {
        val result = daumRequestAdapter.fetchPopularWebtoons()
        return result.map{ it.refine() }
    }
    savePopularWebtoons(daumWebtoons:List<Webtoon>) {
        repository.save(daumWebtoons)
    }
    getWeekdayWebtoons(){
        val result = daumRequestAdapter.fetchWeekdayWebtoons()
        return result.map{it.refine()}
    }
    saveWeekdayWebtoons(daumWebtoons:List<Webtoon>) {
        repository.save(daumWebtoons)
    }
}
```

인기별, 요일별 웹툰을 각각 가져와서 저장하는 코드로 해석되는데 해당 작업들이 필요한지 궁금합니다. ( 구조변경 전 작성해주신 가이드 라인이라 다른게 맞을까요? 아니면 필요한 작업들인지 궁금해서 질문드립니다! )

**Comment by devsejong** [comment]
아뉴 어떻게든 요구사항만 만족하면 되는거라서 문제없어요 :)

**Comment by devsejong** [comment]
제가 이번주는 진행이 늦네요 ㅠㅠ

**Comment by jadenkim94** [comment]
넵넵 ㅎㅎ  감사합니다 😄  빨리 진행하셨으면 제가 못따라갔을수도,,, 오히려 좋았습니다 ㅎㅎ
