### ISSUE TITLE
웹툰을 기준으로 스토리/작화/종합점수의 평균과 평가수를 반환할 수 있다.

### ISSUE THREAD

**Issue by devsejong** [depromeet/webtoon#44]
* [x] 웹툰별 평균점수를 테이블에 저장할 수 있어야 한다.
* [x] 평점이 추가될때마다 평점이 재계산된다.
* [x] 상세페이지 호출시 해당 평점을 반환할 수 있어야 한다.

**Comment by jadenkim94** [comment]
* 사용자 중복 처리 -> 특정 웹툰에 대해 특정 사용자는 한번만 평점을 매길 수 있다. 


평점 추가 flow 
parameter( 사용자 id,  웹툰 id, story 점수, drawing 점수) 

#1 평점 테이블에서 동일한 사용자id&웹툰id  가 있는지 확인한다. -> 있다면 중복 평가 불가

#2 받은 데이터를 가지고 평점 테이블 업데이트

#3 평균평점테이블 업데이트 
totalStoryScore += 입력받은 story점수,
totalDrawingScore += 입력받은 drawing 점수,  
votes += 1,
totalStoryAverage = (new) totalStoryScore / (new) votes,
totalDrawingScore = (new) totalDrawingScore/ (new) votes,
totalAverage =  ((new)totalStoryAverage + (new)totalDrawingScore)/2
