### ISSUE TITLE
개발환경 구성 - 백엔드서버 설정

### ISSUE THREAD

**Issue by jadenkim94** [depromeet/webtoon#7]
*완료목표*

* AWS에 ec2 서버를 띄우고 배포환경을 구성한다.
* git 저장소에서 develop으로 커밋시 API 서버를 배포한다
* mysql을 설정한다.
  * database는 배치, API, Admin용도를 분리한다.
* 외부에서는 API를 호출할 수 있어야 한다.

**Comment by devsejong** [comment]
https://webtoon.chandol.net 으로 접속 가능
github 커밋시 자동으로 배포 되도록 설정완료
ssl 설정완료 : 성능이슈있음. 추후 고민할것
