### ISSUE TITLE
API 문서 제공하기 

### ISSUE THREAD

**Issue by jadenkim94** [depromeet/webtoon#8]

**Comment by devsejong** [comment]
* https://spring.io/projects/spring-restdocs
* https://swagger.io/specification

API 문서를 기준으로 프론트분들이 작업을 할 수 있고 이 스펙을 바탕으로 백엔드와 통신하게 됩니다.
둘중 하나의 기술을 선택하고 이를 바탕으로 프로젝트에 설정을 부탁드릴께요.

**Comment by devsejong** [comment]
https://www.notion.so/depromeet/04-24-f589dff7a5144fa4976a54724a041746
여기 링크에 맞추어서 공통 리스폰스와 API 구성을 부탁드릴께요.
